### ISSUE TITLE
Some little refactorings

### ISSUE THREAD

**Issue by justinrlle** [wesleywiser/process_path#2]
Hi, I saw the other day your post on [/r/rust](https://reddit.com/r/rust), and I have a few remarks which could simplify the code (not much, but still, I think they're may be more idiomatic).

The first one is one the exported function `get_executable_path`. Instead of exporting a function which calls always the same function (`os::get_executable_path()`), you just re-export it:
```rust
// before
pub fn get_executable_path() -> Option<PathBuf> {
    os::get_executable_path()
}
// after
pub use os::get_executable_path;
```
In fact you could do this when you rename the different modules, but I don't think it adds much:
```rust
#[cfg(target_os = "linux")]
// before
use linux as os;
// after
pub use linux::get_executable_path;
```
But you use the solutions that suits you best, of course!

I have a second remark, and it's about the platforms. Even though compiling `winapi` and `kernel32` on another platform than Windows won't be compiled, they will still be fetched, and it's the same for the `libc` depencie. You just need to add the right `#[cfg(...)]` before the `extern crate ...`, and specify in the [Cargo.toml](../blob/master/Cargo.toml) the dependencies to be [platform dependent](http://doc.crates.io/specifying-dependencies.html#platform-specific-dependencies):
```toml
[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
[taget.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
```

I haven't tested these "fixes", but they should work, and show how elegant Rust can be!

**Comment by wesleywiser** [comment]
Thanks @justinrlle! 

Regarding your first comment, I did that intentionally to enforce all that all of the os-specific functions have the same signature. If an os-specific function changed for some reason, this would cause a compilation error in this crate rather than, potentially, one in a consuming crate.

Regarding your second comment, that is very cool! I didn't know you could do that. I'd be happy to take a PR that implements that change (or I might do it myself if I have time).

**Comment by justinrlle** [comment]
I'll do the changes and submit a PR for the platform dependents crates, and test it on MacOS, Windows, and Linux (yup, all the platforms), no problem for me!

Regarding the exported function, I get what you're saying, and I'm asking myself if there is a way to be sure that the exported function will be always the same, regardless of the platform...

**Comment by wesleywiser** [comment]
Closing this since it's done. If you think of anything else, feel free to open another issue or a pull request. Thanks
