### ISSUE TITLE
Please push 0.1.4 to crates.io

### ISSUE THREAD

**Issue by philip-lamb** [wesleywiser/process_path#8]
Current version on crates.io does not have fix for Windows dll path length overflow. Please update.

**Comment by Eathox** [comment]
Bump. @wesleywiser when you have some spare time could you please update.

**Comment by wesleywiser** [comment]
Sorry for the delay!!! 

[0.1.4 is out](https://github.com/wesleywiser/process_path/releases/tag/0.1.4) and on crates.io.
